### ISSUE TITLE
Curly import indentation should respect indentation option

### ISSUE THREAD

**Issue by FrancisMurillo** [magicdawn/esformatter-curly#2]
If I set my `indent` options as `\t`, the indentation for imports remain as two spaces `  `. It works for object expressions but not for imports or am I missing some magic configuration?

Good work by the way.

**Comment by magicdawn** [comment]
I found out that a plugin should take care of the options too. https://github.com/millermedeiros/esformatter/blob/master/doc/plugins.md#setoptionsoptions

**Comment by magicdawn** [comment]
this should be fixed at v0.0.2
see https://github.com/magicdawn/esformatter-curly/tree/v0.0.2/examples/issue2

**Comment by magicdawn** [comment]
I'm closing this, if anything wrong, let me know.
